# Let's start with the basics: this is a PHP project
language: php

# Run on top of a few versions to check compatibility
php:
  - 5.6
  - 7.0
  - nightly

# Install Composer package before testing
install:
  - composer install --no-interaction
